#ARG base_image=crmdvrepo01.azurecr.io/wildfly:310122

ARG baseImageTag
FROM crmdvrepo01.azurecr.io/hmcts/wildfly:${baseImageTag}

ARG version
ARG repo_loc=https://libraries-internal.mdv.cpp.nonlive/artifactory/repocentral

# We should remove these properties:
#
# This context only has one database: stagingdcs. None of
# the normal framework databases exist; therefore we shouldn't need to run liquibase
# here and these framework versions don't need to exist.
#
# Leaving them here for now so nothing breaks
ARG wildfly_home=/opt/jboss/wildfly
ARG wildfly_user=jboss
ARG context_group_name=staging/dcs
ARG context_name=stagingdcs
ARG framework_version=17.100.4
ARG framework_libraries_version=17.100.1

# service war file
ADD ${repo_loc}/uk/gov/moj/cpp/${context_group_name}/${context_name}-service/${version}/${context_name}-service-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/${context_name}-service-${version}.war

# liquibase jars & config
RUN mkdir /tmp/liquibase
ADD ${repo_loc}/uk/gov/moj/cpp/${context_group_name}/${context_name}-liquibase/${version}/${context_name}-liquibase-${version}.jar /tmp/liquibase/${context_name}-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/services/framework-system-liquibase/${framework_version}/framework-system-liquibase-${framework_version}.jar  /tmp/liquibase/framework-system-liquibase.jar
ADD ${repo_loc}/uk/gov/justice/services/jobstore-liquibase/${framework_libraries_version}/jobstore-liquibase-${framework_libraries_version}.jar  /tmp/liquibase/jobstore-liquibase.jar

RUN chmod -R 755 /tmp/liquibase
COPY scripts/liquibase.sh /tmp/liquibase/liquibase.sh
RUN chown ${wildfly_user}:${wildfly_user} /tmp/liquibase/liquibase.sh && chmod 755 /tmp/liquibase/liquibase.sh
RUN mkdir /opt/cpp-tools
ADD ${repo_loc}/uk/gov/justice/services/framework-jmx-command-client/${framework_version}/framework-jmx-command-client-${framework_version}.jar /opt/cpp-tools/framework-jmx-command-client.jar
RUN chown ${wildfly_user}:${wildfly_user} /opt/cpp-tools/framework-jmx-command-client.jar && chmod 755 /opt/cpp-tools/framework-jmx-command-client.jar
USER ${wildfly_user}
LABEL base_image ${baseImageTag}