package uk.gov.justice.api.resource;

import static java.util.UUID.randomUUID;
import static javax.json.Json.createObjectBuilder;
import static org.apache.hc.core5.http.HttpStatus.SC_BAD_REQUEST;
import static uk.gov.justice.services.core.annotation.Component.COMMAND_API;
import static uk.gov.justice.services.messaging.JsonEnvelope.envelopeFrom;
import static uk.gov.justice.services.messaging.JsonEnvelope.metadataBuilder;
import static uk.gov.moj.cpp.staging.dcs.domain.common.Constants.ERROR_MESSAGE;

import uk.gov.hmcts.cp.openapi.model.UpdateTransactionStatusRequest;
import uk.gov.justice.services.core.annotation.Adapter;
import uk.gov.justice.services.core.interceptor.InterceptorChainProcessor;
import uk.gov.justice.services.core.interceptor.InterceptorContext;
import uk.gov.justice.services.core.interceptor.spi.InterceptorContextProvider;
import uk.gov.justice.services.messaging.JsonEnvelope;
import uk.gov.moj.cpp.staging.dcs.event.service.DcsOperationHelper;

import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.json.JsonObject;
import javax.ws.rs.core.Response;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.hc.core5.http.HttpStatus;
import org.slf4j.Logger;
/*
* Name of this class same as if it was generated by rest adapters of RAML file. Rest adapter is not generating
* same name class since It is created manually thus it already exists hence this class is not generated again
* by rest adapter. Now this class provides default implementation of rest api in the RAML.
* CommandApiRestStagingdcsApplication This auto generated bean has the reference to this class.
* Do not change the name of the class unless the api signature changes in the RAML
*/
@SuppressWarnings({"squid:S3740", "squid:S6813","java:S2221"})
@Stateless
@Adapter(COMMAND_API)
public class DefaultCommandApiTransactionTransactionRefResource implements CommandApiTransactionTransactionRefResource {
    public static final String TRANSACTION_REF = "transactionRef";
    private static final String ACTION_NAME_RENDER = "stagingdcs.process-dcs-transaction-status";
    @Inject
    private Logger logger;
    @Inject
    private DcsOperationHelper dcsOperationHelper;
    @Inject
    private InterceptorChainProcessor interceptorChainProcessor;
    @Inject
    private InterceptorContextProvider interceptorContextProvider;

    @Override
    public Response processTransactionStatus(final String userId, final String transactionRef, final JsonObject payload) {
        logger.info("Process Dcs Transaction API with transaction Id : {}", transactionRef);
        final JsonEnvelope query = envelopeFrom(metadataBuilder().withId(randomUUID()).withName(ACTION_NAME_RENDER).withUserId(userId).build(), payload);
        final InterceptorContext interceptorContext = interceptorContextProvider.interceptorContextWithInput(query);
        interceptorChainProcessor.process(interceptorContext);
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            final UpdateTransactionStatusRequest request = objectMapper.readValue(payload.toString(), UpdateTransactionStatusRequest.class);
            dcsOperationHelper.updateTransactionStatus(transactionRef, request);
        } catch (Exception ex) {
            return sendBadRequestResponse(ex, transactionRef);
        }

        return Response.status(HttpStatus.SC_ACCEPTED).build();
    }

    private Response sendBadRequestResponse(final Exception ex, final String transactionRef) {
        final JsonObject responsePayload = createObjectBuilder()
                .add(TRANSACTION_REF, transactionRef)
                .add(ERROR_MESSAGE, ex.getMessage())
                .build();
        return Response.status(SC_BAD_REQUEST)
                .entity(responsePayload.toString())
                .build();
    }
}