package uk.gov.moj.cpp.staging.dcs.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import uk.gov.moj.cpp.staging.dcs.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;


rule "Query - Create Case Request"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingdcs.create-case-defendant-file-in-dcs");

  then
    $outcome.setSuccess(true);
end